// <auto-generated />
using System;
using FintechPayments.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FintechPayments.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20260918105820_AddTransactionalOutbox")]
    partial class AddTransactionalOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FintechPayments.Domain.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_events_correlation");

                    b.HasIndex("ActorId", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_actor_created");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt")
                        .HasDatabaseName("ix_audit_events_entity_created");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("FintechPayments.Domain.Auditing.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("FintechPayments.Domain.Ledger.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("direction");

                    b.Property<Guid>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("LedgerTransactionId");

                    b.HasIndex("WalletId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_ledger_entries_wallet_created_id");

                    b.ToTable("ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledger_entries_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_ledger_entries_currency_length", "char_length(currency) = 3");
                        });
                });

            modelBuilder.Entity("FintechPayments.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_transactions_reference");

                    b.HasIndex("TransferId")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_transactions_transfer_id")
                        .HasFilter("transfer_id IS NOT NULL");

                    b.ToTable("ledger_transactions", (string)null);
                });

            modelBuilder.Entity("FintechPayments.Domain.Payments.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_hash")
                        .IsFixedLength();

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("state");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_expires_at");

                    b.HasIndex("TransferId")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_transfer_id")
                        .HasFilter("transfer_id IS NOT NULL");

                    b.HasIndex("ActorId", "Operation", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_actor_operation_key");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("FintechPayments.Domain.Reconciliation.ReconciliationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<decimal?>("ExternalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("external_amount");

                    b.Property<decimal?>("InternalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("internal_amount");

                    b.Property<Guid>("ReconciliationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconciliation_run_id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.HasKey("Id");

                    b.HasIndex("ReconciliationRunId", "Category")
                        .HasDatabaseName("ix_reconciliation_items_run_category");

                    b.ToTable("reconciliation_items", (string)null);
                });

            modelBuilder.Entity("FintechPayments.Domain.Reconciliation.ReconciliationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DiscrepancyCount")
                        .HasColumnType("integer")
                        .HasColumnName("discrepancy_count");

                    b.Property<decimal>("ExternalTotal")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("external_total");

                    b.Property<string>("InputChecksum")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("input_checksum");

                    b.Property<decimal>("InternalTotal")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("internal_total");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer")
                        .HasColumnName("matched_count");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "PeriodStart", "PeriodEnd", "InputChecksum")
                        .IsUnique()
                        .HasDatabaseName("ux_reconciliation_runs_identity");

                    b.ToTable("reconciliation_runs", (string)null);
                });

            modelBuilder.Entity("FintechPayments.Domain.Settlements.SettlementBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AdjustmentAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("adjustment_amount");

                    b.Property<string>("AdjustmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("adjustment_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<decimal>("FeeAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fee_amount");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<Guid?>("FinalizedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("finalized_by");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("gross_amount");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("net_amount");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<Guid>("ReconciliationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconciliation_run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReconciliationRunId");

                    b.HasIndex("Status", "Currency", "PeriodStart", "PeriodEnd")
                        .HasDatabaseName("ix_settlement_batches_period");

                    b.ToTable("settlement_batches", (string)null);
                });

            modelBuilder.Entity("FintechPayments.Domain.Settlements.SettlementItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ReconciliationItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconciliation_item_id");

                    b.Property<Guid>("SettlementBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_batch_id");

                    b.HasKey("Id");

                    b.HasIndex("ReconciliationItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_settlement_items_reconciliation_item");

                    b.HasIndex("SettlementBatchId");

                    b.ToTable("settlement_items", (string)null);
                });

            modelBuilder.Entity("FintechPayments.Domain.Transfers.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<Guid>("DestinationWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_wallet_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<Guid>("SourceWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_wallet_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_transfers_reference");

                    b.HasIndex("DestinationWalletId", "CreatedAt")
                        .HasDatabaseName("ix_transfers_destination_created");

                    b.HasIndex("SourceWalletId", "CreatedAt")
                        .HasDatabaseName("ix_transfers_source_created");

                    b.ToTable("transfers", null, t =>
                        {
                            t.HasCheckConstraint("ck_transfers_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_transfers_distinct_wallets", "source_wallet_id <> destination_wallet_id");
                        });
                });

            modelBuilder.Entity("FintechPayments.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FintechPayments.Domain.Wallets.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AvailableBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("available_balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_wallets_owner_currency");

                    b.ToTable("wallets", null, t =>
                        {
                            t.HasCheckConstraint("ck_wallets_balance_non_negative", "available_balance >= 0");

                            t.HasCheckConstraint("ck_wallets_currency_length", "char_length(currency) = 3");
                        });
                });

            modelBuilder.Entity("FintechPayments.Domain.Webhooks.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ProviderTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ExternalEventId")
                        .IsUnique();

                    b.HasIndex("Status", "ReceivedAt");

                    b.ToTable("webhook_events", (string)null);
                });

            modelBuilder.Entity("FintechPayments.Domain.Ledger.LedgerEntry", b =>
                {
                    b.HasOne("FintechPayments.Domain.Ledger.LedgerTransaction", null)
                        .WithMany("Entries")
                        .HasForeignKey("LedgerTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FintechPayments.Domain.Wallets.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FintechPayments.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.HasOne("FintechPayments.Domain.Transfers.Transfer", null)
                        .WithOne()
                        .HasForeignKey("FintechPayments.Domain.Ledger.LedgerTransaction", "TransferId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FintechPayments.Domain.Payments.IdempotencyRecord", b =>
                {
                    b.HasOne("FintechPayments.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FintechPayments.Domain.Transfers.Transfer", null)
                        .WithOne()
                        .HasForeignKey("FintechPayments.Domain.Payments.IdempotencyRecord", "TransferId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FintechPayments.Domain.Reconciliation.ReconciliationItem", b =>
                {
                    b.HasOne("FintechPayments.Domain.Reconciliation.ReconciliationRun", null)
                        .WithMany("Items")
                        .HasForeignKey("ReconciliationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FintechPayments.Domain.Settlements.SettlementBatch", b =>
                {
                    b.HasOne("FintechPayments.Domain.Reconciliation.ReconciliationRun", null)
                        .WithMany()
                        .HasForeignKey("ReconciliationRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FintechPayments.Domain.Settlements.SettlementItem", b =>
                {
                    b.HasOne("FintechPayments.Domain.Settlements.SettlementBatch", null)
                        .WithMany("Items")
                        .HasForeignKey("SettlementBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FintechPayments.Domain.Transfers.Transfer", b =>
                {
                    b.HasOne("FintechPayments.Domain.Wallets.Wallet", null)
                        .WithMany()
                        .HasForeignKey("DestinationWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FintechPayments.Domain.Wallets.Wallet", null)
                        .WithMany()
                        .HasForeignKey("SourceWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FintechPayments.Domain.Wallets.Wallet", b =>
                {
                    b.HasOne("FintechPayments.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FintechPayments.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("FintechPayments.Domain.Reconciliation.ReconciliationRun", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FintechPayments.Domain.Settlements.SettlementBatch", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
